# -*- coding: utf-8 -*-
"""PROYECTO_regresion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ob0qUtQNkkKi10HqRdxwfovwZMuLcd2D
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

videojuegos = pd.read_csv("Video_Games_Sales.csv")

videojuegos.head()

videojuegos.shape

videojuegos.isnull().sum()

videojuegos.dropna(inplace = True)

videojuegos.isnull().sum()

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(14, 8))
sns.barplot(x=videojuegos['Global_Sales'].head(30), y=videojuegos["Name"].head(30), palette="viridis")
plt.title("Ventas Globales de los Videojuegos Más Vendidos (en millones)", fontsize=16)
plt.xlabel("Ventas Globales (millones)")
plt.ylabel("Título del Videojuego")
plt.tight_layout()
plt.show()

plt.figure(figsize=(12, 6))
sns.barplot(x='Genre', y='Global_Sales', data=videojuegos, palette='viridis')
plt.title('Top-selling Genres')
plt.xlabel('Genre')
plt.ylabel('Global Sales (in millions)')
plt.xticks(rotation=45)
plt.show()

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import LabelEncoder

le_platform = LabelEncoder()
le_genre = LabelEncoder()
le_publisher = LabelEncoder()

videojuegos['Platform'] = le_platform.fit_transform(videojuegos['Platform'])
videojuegos['Genre'] = le_genre.fit_transform(videojuegos['Genre'])
videojuegos['Publisher'] = le_publisher.fit_transform(videojuegos['Publisher'])

X = videojuegos[['Platform', 'Year', 'Genre', 'Publisher', 'NA_Sales', 'JP_Sales', 'Other_Sales']]
y = videojuegos['EU_Sales']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = RandomForestRegressor(n_estimators=100, random_state=42)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

# Mostrar los resultados
print(f"Error cuadrático medio (MSE): {mse}")
print(f"Coeficiente de determinación (R²): {r2}")

nuevo_juego = {
    'Platform': 'PC',
    'Year': 2025,
    'Genre': 'Action',
    'Publisher': 'Capcom',
    'NA_Sales': 10.0,
    'JP_Sales': 2.5,
    'Other_Sales': 5.3
}

nuevo_df = pd.DataFrame([nuevo_juego])

nuevo_df['Platform'] = le_platform.transform(nuevo_df['Platform'])
nuevo_df['Genre'] = le_genre.transform(nuevo_df['Genre'])
nuevo_df['Publisher'] = le_publisher.transform(nuevo_df['Publisher'])

prediccion = model.predict(nuevo_df)
print(f"Predicción de ventas en Europa: {prediccion[0]:.2f} millones")